/**
 * PDF usage report.
 *
 * Generated client-side with jsPDF so no server round-trip or headless browser
 * is needed, and so a Vercel function never has to hold a large buffer.
 *
 * NON-NEGOTIABLE CONTENT RULES (spec §29, §68):
 *   - a DEMO / SIMULATION REPORT banner on page 1 whenever the data source is
 *     simulated, plus a watermark on every page
 *   - every financial and emissions figure labelled as an estimate, with the
 *     assumptions that produced it printed in the document
 *   - no secrets, no connection strings, no tokens, ever
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

import type { Alert, AppMode, BillingAssumptions, UsageRecord } from '@shared/types';
import type { BillResult } from '@shared/billing';
import { ESTIMATE_DISCLAIMER } from '@shared/billing';

export interface ReportInput {
  record: UsageRecord;
  bill: BillResult;
  assumptions: BillingAssumptions;
  dataSource: AppMode;
  nodes: Array<{ shortName: string; type: string; ratedPower: number }>;
  alerts?: Alert[];
  anomalyCount?: number;
  recommendations?: string[];
  generatedBy?: string;
}

const COLORS = {
  ink: [15, 23, 42] as [number, number, number],
  muted: [100, 116, 139] as [number, number, number],
  accent: [2, 132, 199] as [number, number, number],
  warn: [180, 83, 9] as [number, number, number],
  line: [203, 213, 225] as [number, number, number],
};

const MARGIN = 16;

export function generateUsageReport(input: ReportInput): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const simulated = input.dataSource === 'SIMULATION';

  let y = MARGIN;

  // ---------------- header ----------------
  doc.setFillColor(...COLORS.accent);
  doc.rect(0, 0, pageWidth, 26, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(17);
  doc.text('GridSync', MARGIN, 13);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.text(
    'Intelligent Monitoring, Predictive Maintenance and Optimization for Renewable Microgrids',
    MARGIN,
    19.5,
  );

  doc.setFontSize(8);
  doc.text('Usage Report', pageWidth - MARGIN, 13, { align: 'right' });
  doc.text(new Date().toLocaleString(), pageWidth - MARGIN, 19.5, { align: 'right' });

  y = 34;

  // ---------------- simulation banner ----------------
  if (simulated) {
    doc.setFillColor(254, 243, 199);
    doc.setDrawColor(245, 158, 11);
    doc.roundedRect(MARGIN, y, pageWidth - MARGIN * 2, 16, 1.5, 1.5, 'FD');

    doc.setTextColor(...COLORS.warn);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('DEMO / SIMULATION REPORT', MARGIN + 4, y + 6.5);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.text(
      'All telemetry in this report was generated by the GridSync simulator. It is not measured hardware data.',
      MARGIN + 4,
      y + 12,
    );
    y += 22;
  }

  // ---------------- period ----------------
  doc.setTextColor(...COLORS.ink);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Report period', MARGIN, y);
  y += 5;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  const start = new Date(input.record.periodStart);
  const end = new Date(input.record.periodEnd);
  const days = Math.max(1, (end.getTime() - start.getTime()) / 86_400_000);
  doc.text(
    `${start.toLocaleString()}  to  ${end.toLocaleString()}   (${days.toFixed(1)} days)`,
    MARGIN,
    y,
  );
  y += 4;
  doc.text(`Data source: ${input.dataSource}`, MARGIN, y);
  if (input.generatedBy) {
    doc.text(`Generated by: ${input.generatedBy}`, pageWidth - MARGIN, y, { align: 'right' });
  }
  y += 8;

  // ---------------- energy summary ----------------
  autoTable(doc, {
    startY: y,
    head: [['Energy summary', 'Value']],
    body: [
      ['Energy generated', `${input.record.energyGeneratedKwh.toFixed(3)} kWh`],
      ['Energy consumed', `${input.record.energyConsumedKwh.toFixed(3)} kWh`],
      ['Grid import', `${input.record.gridImportKwh.toFixed(3)} kWh`],
      ['Average daily consumption', `${input.record.averageDailyKwh.toFixed(3)} kWh/day`],
      ['Peak demand', `${input.record.peakDemandW.toFixed(0)} W`],
      ['Self-sufficiency', `${(input.bill.selfSufficiency * 100).toFixed(1)} %`],
    ],
    theme: 'striped',
    headStyles: { fillColor: COLORS.accent, fontSize: 9 },
    bodyStyles: { fontSize: 8.5, textColor: COLORS.ink },
    margin: { left: MARGIN, right: MARGIN },
  });
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;

  // ---------------- nodes ----------------
  if (input.nodes.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [['Node', 'Type', 'Rated power']],
      body: input.nodes.map((n) => [n.shortName, n.type.replace('_', ' '), `${n.ratedPower} W`]),
      theme: 'striped',
      headStyles: { fillColor: COLORS.accent, fontSize: 9 },
      bodyStyles: { fontSize: 8.5 },
      margin: { left: MARGIN, right: MARGIN },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  }

  // ---------------- cost estimate ----------------
  const cur = input.assumptions.currency === 'INR' ? 'Rs.' : input.assumptions.currency;
  const money = (n: number) => `${cur} ${n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

  autoTable(doc, {
    startY: y,
    head: [['Cost estimate', 'Value']],
    body: [
      ['Grid energy charge', money(input.bill.energyCharge)],
      ['Fixed charge', money(input.bill.fixedCharge)],
      ['Additional charges', money(input.bill.additionalCharges)],
      ['Estimated bill', money(input.bill.estimatedBill)],
      ['Bill if fully grid-supplied', money(input.bill.billWithoutMicrogrid)],
      ['Estimated saving', money(input.bill.estimatedSavings)],
      ['Diesel litres avoided', `${input.bill.dieselLitresAvoided.toFixed(2)} L`],
      ['Diesel-equivalent cost avoided', money(input.bill.dieselEquivalentCost)],
      ['Estimated CO2 avoided', `${input.bill.estimatedCo2AvoidedKg.toFixed(2)} kg`],
    ],
    theme: 'striped',
    headStyles: { fillColor: COLORS.accent, fontSize: 9 },
    bodyStyles: { fontSize: 8.5 },
    margin: { left: MARGIN, right: MARGIN },
  });
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;

  // ---------------- assumptions ----------------
  if (y > 220) {
    doc.addPage();
    y = MARGIN;
  }

  autoTable(doc, {
    startY: y,
    head: [['Assumption', 'Value']],
    body: [
      ['Tariff', `${cur} ${input.assumptions.tariffPerKwh} / kWh`],
      ['Fixed charge', `${cur} ${input.assumptions.fixedCharge}`],
      ['Additional charge rate', `${(input.assumptions.additionalChargeRate * 100).toFixed(1)} %`],
      ['Diesel price', `${cur} ${input.assumptions.dieselPricePerLitre} / L`],
      ['Generator yield', `${input.assumptions.generatorKwhPerLitre} kWh / L`],
      ['Grid emission factor', `${input.assumptions.gridEmissionFactor} kg CO2 / kWh`],
    ],
    theme: 'grid',
    headStyles: { fillColor: COLORS.muted, fontSize: 9 },
    bodyStyles: { fontSize: 8.5 },
    margin: { left: MARGIN, right: MARGIN },
  });
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;

  // ---------------- calculation transparency ----------------
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.ink);
  doc.text('Calculation', MARGIN, y);
  y += 5;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...COLORS.muted);
  for (const f of input.bill.formulas) {
    if (y > 268) {
      doc.addPage();
      y = MARGIN;
    }
    doc.text(`${f.label}: ${f.expression}`, MARGIN, y);
    y += 3.6;
    doc.text(`   ${f.value}`, MARGIN, y);
    y += 4.6;
  }
  y += 3;

  // ---------------- alerts ----------------
  if (input.alerts && input.alerts.length > 0) {
    if (y > 210) {
      doc.addPage();
      y = MARGIN;
    }
    autoTable(doc, {
      startY: y,
      head: [['Time', 'Node', 'Severity', 'Condition', 'Source']],
      body: input.alerts
        .slice(0, 18)
        .map((a) => [
          new Date(a.timestamp).toLocaleString(),
          a.nodeId ?? 'system',
          a.severity,
          a.condition,
          `${a.source} (${a.kind})`,
        ]),
      theme: 'striped',
      headStyles: { fillColor: COLORS.accent, fontSize: 8.5 },
      bodyStyles: { fontSize: 7.5 },
      columnStyles: { 3: { cellWidth: 60 } },
      margin: { left: MARGIN, right: MARGIN },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
  }

  if (input.anomalyCount !== undefined) {
    doc.setFontSize(8.5);
    doc.setTextColor(...COLORS.muted);
    doc.text(
      `Model-predicted anomalies in this period: ${input.anomalyCount}`,
      MARGIN,
      y,
    );
    y += 6;
  }

  // ---------------- recommendations ----------------
  if (input.recommendations && input.recommendations.length > 0) {
    if (y > 245) {
      doc.addPage();
      y = MARGIN;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.ink);
    doc.text('Recommendations', MARGIN, y);
    y += 5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    for (const rec of input.recommendations) {
      const lines = doc.splitTextToSize(`- ${rec}`, pageWidth - MARGIN * 2);
      if (y + lines.length * 3.8 > 275) {
        doc.addPage();
        y = MARGIN;
      }
      doc.text(lines, MARGIN, y);
      y += lines.length * 3.8 + 1.5;
    }
    y += 3;
  }

  // ---------------- disclaimer ----------------
  if (y > 250) {
    doc.addPage();
    y = MARGIN;
  }
  doc.setDrawColor(...COLORS.line);
  doc.line(MARGIN, y, pageWidth - MARGIN, y);
  y += 5;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.warn);
  doc.text('Important', MARGIN, y);
  y += 4;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.muted);
  const notes = [
    ESTIMATE_DISCLAIMER,
    simulated
      ? 'This report was produced from SIMULATED telemetry generated by the GridSync simulation engine. It does not describe a physical installation and must not be presented as measured project results.'
      : 'This report was produced from telemetry recorded by the GridSync platform.',
    'Energy totals are integrated from down-sampled telemetry and are approximations at the resolution of the stored series, not meter readings.',
  ];
  for (const note of notes) {
    const lines = doc.splitTextToSize(note, pageWidth - MARGIN * 2);
    doc.text(lines, MARGIN, y);
    y += lines.length * 3.2 + 2;
  }

  // ---------------- footer + watermark on every page ----------------
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    if (simulated) {
      // Diagonal watermark so a printed page cannot be mistaken for real data.
      doc.saveGraphicsState();
      // @ts-expect-error — GState is present at runtime but missing from the types
      doc.setGState(new doc.GState({ opacity: 0.07 }));
      doc.setTextColor(245, 158, 11);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(52);
      doc.text('SIMULATION', pageWidth / 2, 160, { align: 'center', angle: 32 });
      doc.restoreGraphicsState();
    }

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.muted);
    doc.text(
      `GridSync usage report  ·  ${input.record.id}  ·  ${input.dataSource}`,
      MARGIN,
      288,
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - MARGIN, 288, { align: 'right' });
  }

  return doc;
}

export function downloadUsageReport(input: ReportInput): void {
  const doc = generateUsageReport(input);
  const stamp = new Date(input.record.periodEnd).toISOString().slice(0, 10);
  const prefix = input.dataSource === 'SIMULATION' ? 'gridsync-DEMO-report' : 'gridsync-report';
  doc.save(`${prefix}-${stamp}.pdf`);
}
