/**
 * AI / Predictive Intelligence.
 *
 * THE HONESTY RULES ARE THE POINT OF THIS PAGE (spec §21, §47, §48, §68):
 *
 *  - Every metric shown comes from ml/models/metrics.json, written by the real
 *    evaluation pipeline on a held-out test split. Nothing is hardcoded.
 *  - The synthetic-training-data warning is displayed prominently, not buried.
 *  - When the pipeline reports insufficient data, its exact sentence is shown
 *    INSTEAD of a number.
 *  - Feature contributions are described as model signals, never as proof of a
 *    physical cause.
 *  - If no model exists, the page says so and notes that the rule engine is
 *    unaffected — it does not invent a prediction.
 */

import { useEffect, useState } from 'react';
import {
  AlertTriangle,
  BrainCircuit,
  FlaskConical,
  Info,
  RefreshCw,
  ShieldCheck,
} from 'lucide-react';

import type { Prediction } from '@shared/types';
import {
  EmptyState,
  ErrorState,
  KindBadge,
  LoadingState,
  Metric,
  Panel,
  fmt,
  fmtDateTime,
  fmtPercent,
} from '../components/ui';
import { errorMessage, intelligenceApi, type PredictionsResponse } from '../lib/api';
import { useTelemetry } from '../lib/telemetry/TelemetryContext';

export default function Intelligence() {
  const { nodes } = useTelemetry();
  const [data, setData] = useState<PredictionsResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = () => {
    setLoading(true);
    intelligenceApi
      .predictions(60)
      .then((res) => {
        setData(res);
        setError(null);
      })
      .catch((err) => setError(errorMessage(err)))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    load();
    const id = window.setInterval(load, 10_000);
    return () => window.clearInterval(id);
  }, []);

  if (loading && !data) return <LoadingState label="Loading model output" />;
  if (error) return <ErrorState message={error} onRetry={load} />;
  if (!data) return null;

  const { model, metrics, latest, recent } = data;

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="flex items-center gap-2 text-xl font-semibold tracking-tight text-slate-50">
            <BrainCircuit className="h-5 w-5 text-violet-400" strokeWidth={1.75} />
            AI / Predictive Intelligence
          </h1>
          <p className="mt-1 text-xs text-slate-500">
            Statistical fault classification, presented separately from the deterministic rule
            engine.
          </p>
        </div>
        <button onClick={load} className="btn btn-secondary btn-sm">
          <RefreshCw className={`h-3.5 w-3.5 ${loading ? 'animate-spin' : ''}`} />
          Refresh
        </button>
      </div>

      {/* ================= no model ================= */}
      {!model.available ? (
        <Panel>
          <EmptyState
            icon={<BrainCircuit className="h-7 w-7" />}
            title="No trained model is available"
            description={
              model.error ??
              'Train one with: npm run ml:pipeline. The deterministic rule engine continues to operate normally and is unaffected.'
            }
          />
        </Panel>
      ) : (
        <>
          {/* ---- synthetic-data warning, first and prominent ---- */}
          {model.trainedOnSyntheticData && (
            <div className="rounded-md border border-amber-500/30 bg-amber-500/5 p-4">
              <div className="flex items-start gap-3">
                <FlaskConical className="mt-0.5 h-4 w-4 shrink-0 text-amber-400" />
                <div>
                  <p className="text-sm font-medium text-amber-200">
                    Model trained on synthetic data
                  </p>
                  <p className="mt-1.5 text-xs leading-relaxed text-amber-200/70">
                    This classifier was trained on telemetry generated by the GridSync simulator,
                    not on measured hardware. The metrics below describe how separable the simulated
                    scenario regimes are. They are <strong>not</strong> validated real-world
                    fault-detection performance and must not be cited as such.
                  </p>
                  <p className="mt-2 text-2xs leading-relaxed text-slate-500">
                    Replace with metrics computed from labelled hardware telemetry before making any
                    performance claim.
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* ---- rules vs ML separation ---- */}
          <div className="rounded-md border border-panel-700 bg-panel-850 p-4">
            <div className="flex items-start gap-3">
              <ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-400" />
              <div>
                <p className="text-sm font-medium text-slate-200">
                  Deterministic safety rules are independent of this model
                </p>
                <p className="mt-1.5 text-xs leading-relaxed text-slate-500">
                  The rule engine evaluates every frame regardless of model availability or output,
                  and nothing on this page can suppress or override a rule. Model results are
                  advisory and are always labelled{' '}
                  <span className="text-violet-300">PREDICTED</span> rather than{' '}
                  <span className="text-slate-300">DETECTED</span>.
                </p>
              </div>
            </div>
          </div>

          {/* ---- model card ---- */}
          <div className="grid gap-4 lg:grid-cols-[1fr_1.3fr]">
            <Panel title="Model" subtitle={model.algorithm}>
              <div className="grid grid-cols-2 gap-4">
                <Metric label="Version" value={model.version ?? '—'} size="sm" />
                <Metric label="Classes" value={model.classes.length} size="sm" />
                {metrics.available && (
                  <>
                    <Metric
                      label="Training rows"
                      value={(metrics.trainSize ?? 0).toLocaleString()}
                      size="sm"
                    />
                    <Metric
                      label="Held-out test rows"
                      value={(metrics.testSize ?? 0).toLocaleString()}
                      size="sm"
                    />
                  </>
                )}
              </div>

              {metrics.available && metrics.splitStrategy && (
                <p className="mt-4 flex items-start gap-2 border-t border-panel-800 pt-3 text-2xs leading-relaxed text-slate-500">
                  <Info className="mt-0.5 h-3 w-3 shrink-0" />
                  Split strategy: {metrics.splitStrategy}
                </p>
              )}

              {metrics.available && metrics.trainedAt && (
                <p className="mt-2 text-2xs text-slate-600">
                  Evaluated {fmtDateTime(metrics.trainedAt)}
                </p>
              )}
            </Panel>

            {/* ---- metrics ---- */}
            <Panel title="Held-out performance" subtitle="Computed by the evaluation pipeline">
              {!metrics.available ? (
                <EmptyState
                  title="No evaluation has been run"
                  description={'note' in metrics ? metrics.note : 'Run: npm run ml:evaluate'}
                />
              ) : metrics.insufficientDataNote ? (
                // Show the pipeline's own sentence rather than a number.
                <div className="rounded border border-amber-500/30 bg-amber-500/5 p-3">
                  <p className="text-xs font-medium text-amber-200">
                    {metrics.insufficientDataNote}
                  </p>
                </div>
              ) : (
                <>
                  <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
                    <Metric label="Accuracy" value={fmtPercent(metrics.accuracy ?? null, 1)} size="sm" />
                    <Metric
                      label="Macro precision"
                      value={fmtPercent(metrics.macroPrecision ?? null, 1)}
                      size="sm"
                    />
                    <Metric
                      label="Macro recall"
                      value={fmtPercent(metrics.macroRecall ?? null, 1)}
                      size="sm"
                    />
                    <Metric label="Macro F1" value={fmtPercent(metrics.macroF1 ?? null, 1)} size="sm" />
                  </div>
                  <p className="mt-3 text-2xs leading-relaxed text-slate-600">
                    Macro averages weight every fault class equally, so a dominant NORMAL class
                    cannot inflate them.
                  </p>
                </>
              )}
            </Panel>
          </div>

          {/* ---- per-class ---- */}
          {metrics.available && metrics.perClass && (
            <Panel
              title="Per-class performance"
              subtitle="Classes with too few held-out examples are withheld rather than estimated"
              bodyClassName=""
            >
              <div className="overflow-x-auto">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Class</th>
                      <th className="text-right">Precision</th>
                      <th className="text-right">Recall</th>
                      <th className="text-right">F1</th>
                      <th className="text-right">Support</th>
                    </tr>
                  </thead>
                  <tbody>
                    {Object.entries(metrics.perClass).map(([label, stats]) => {
                      const s = stats as {
                        precision: number | null;
                        recall: number | null;
                        f1: number | null;
                        support: number;
                        note?: string;
                      };
                      return (
                        <tr key={label}>
                          <td className="font-medium text-slate-200">{label.replace(/_/g, ' ')}</td>
                          {s.precision === null ? (
                            <td colSpan={3} className="text-center text-2xs text-slate-600">
                              {s.note ?? 'Withheld — insufficient support'}
                            </td>
                          ) : (
                            <>
                              <td className="tabular text-right">{fmtPercent(s.precision, 1)}</td>
                              <td className="tabular text-right">{fmtPercent(s.recall, 1)}</td>
                              <td className="tabular text-right">{fmtPercent(s.f1, 1)}</td>
                            </>
                          )}
                          <td className="tabular text-right text-slate-500">
                            {s.support.toLocaleString()}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </Panel>
          )}

          {/* ---- live predictions ---- */}
          <Panel
            title="Current predictions"
            subtitle="Latest model output per node"
            bodyClassName=""
          >
            {latest.length === 0 ? (
              <EmptyState
                title="No predictions yet"
                description="Inference runs once the simulator produces telemetry. Start it with: npm run worker"
              />
            ) : (
              <div className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-3">
                {latest.map((prediction) => (
                  <PredictionCard
                    key={prediction.id}
                    prediction={prediction}
                    nodeName={
                      nodes.find((n) => n.id === prediction.nodeId)?.shortName ?? prediction.nodeId
                    }
                  />
                ))}
              </div>
            )}
          </Panel>

          {/* ---- feature importance ---- */}
          {metrics.available && metrics.featureImportances && metrics.featureImportances.length > 0 && (
            <Panel
              title="Global feature importance"
              subtitle="Impurity-based importance across the whole forest"
            >
              <div className="space-y-2">
                {metrics.featureImportances.slice(0, 10).map((f) => (
                  <div key={f.feature} className="flex items-center gap-3">
                    <span className="w-44 shrink-0 truncate text-2xs text-slate-500">
                      {f.feature}
                    </span>
                    <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-panel-800">
                      <div
                        className="h-full rounded-full bg-violet-500"
                        style={{
                          width: `${(f.importance / metrics.featureImportances![0].importance) * 100}%`,
                        }}
                      />
                    </div>
                    <span className="tabular w-12 shrink-0 text-right text-2xs text-slate-400">
                      {f.importance.toFixed(3)}
                    </span>
                  </div>
                ))}
              </div>
              <p className="mt-4 border-t border-panel-800 pt-3 text-2xs leading-relaxed text-slate-600">
                Global importance describes what the model relies on overall. It is not a causal
                statement, and it does not explain any individual prediction on its own.
              </p>
            </Panel>
          )}

          {/* ---- recent ---- */}
          {recent.length > 0 && (
            <Panel title="Recent inferences" bodyClassName="">
              <div className="overflow-x-auto">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Time</th>
                      <th>Node</th>
                      <th>Predicted class</th>
                      <th className="text-right">Confidence</th>
                      <th>Model</th>
                    </tr>
                  </thead>
                  <tbody>
                    {recent.slice(0, 20).map((p) => (
                      <tr key={p.id}>
                        <td className="text-xs text-slate-500">{fmtDateTime(p.timestamp)}</td>
                        <td>{nodes.find((n) => n.id === p.nodeId)?.shortName ?? p.nodeId}</td>
                        <td>
                          <span
                            className={
                              p.predictedClass === 'NORMAL' ? 'text-slate-400' : 'text-violet-300'
                            }
                          >
                            {p.predictedClass.replace(/_/g, ' ').toLowerCase()}
                          </span>
                        </td>
                        <td className="tabular text-right">{fmtPercent(p.confidence, 0)}</td>
                        <td className="text-xs text-slate-500">{p.modelVersion}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </Panel>
          )}
        </>
      )}
    </div>
  );
}

function PredictionCard({ prediction, nodeName }: { prediction: Prediction; nodeName: string }) {
  const normal = prediction.predictedClass === 'NORMAL';

  return (
    <article
      className={`rounded border p-4 ${
        normal ? 'border-panel-700 bg-panel-850' : 'border-violet-500/30 bg-violet-500/5'
      }`}
    >
      <div className="flex items-start justify-between gap-2">
        <div>
          <p className="text-2xs uppercase tracking-wider text-slate-500">{nodeName}</p>
          <h3
            className={`mt-1 text-sm font-semibold ${normal ? 'text-slate-300' : 'text-violet-200'}`}
          >
            {prediction.predictedClass.replace(/_/g, ' ').toLowerCase()}
          </h3>
        </div>
        <KindBadge kind="PREDICTED" />
      </div>

      {/* confidence */}
      <div className="mt-3">
        <div className="flex items-baseline justify-between">
          <span className="metric-label">Confidence</span>
          <span className="tabular text-sm font-semibold text-slate-100">
            {fmtPercent(prediction.confidence, 1)}
          </span>
        </div>
        <div className="mt-1.5 h-1.5 w-full overflow-hidden rounded-full bg-panel-800">
          <div
            className={`h-full rounded-full ${normal ? 'bg-slate-500' : 'bg-violet-500'}`}
            style={{ width: `${prediction.confidence * 100}%` }}
          />
        </div>
      </div>

      <p className="mt-3 text-2xs leading-relaxed text-slate-400">{prediction.explanation}</p>

      {/* contributing signals */}
      {prediction.contributingFeatures.length > 0 && (
        <div className="mt-3 border-t border-panel-800 pt-3">
          <p className="metric-label">Contributing signals</p>
          <ul className="mt-1.5 space-y-1">
            {prediction.contributingFeatures.map((f) => (
              <li key={f.feature} className="flex items-center justify-between gap-2 text-2xs">
                <span className="truncate text-slate-500">{f.feature}</span>
                <span className="tabular shrink-0 text-slate-300">{fmt(f.value, 2)}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {!normal && (
        <p className="mt-3 rounded border border-panel-700 bg-panel-950/50 p-2.5 text-2xs leading-relaxed text-slate-400">
          <span className="font-medium text-slate-300">Recommended: </span>
          {prediction.recommendedAction}
        </p>
      )}

      <p className="mt-3 flex items-start gap-1.5 text-2xs leading-relaxed text-slate-600">
        <AlertTriangle className="mt-0.5 h-3 w-3 shrink-0" />
        These are model input signals, not proof of a physical cause. Confirm by inspection before
        acting.
      </p>

      <p className="mt-2 text-2xs text-slate-600">
        {prediction.modelVersion} · {fmtDateTime(prediction.timestamp)}
        {prediction.trainedOnSyntheticData && ' · synthetic training data'}
      </p>
    </article>
  );
}
