/**
 * Development seed.
 *
 * Run: npm run seed
 *
 * Creates the node catalogue, demo users, and a short run of historical
 * telemetry so the charts are not empty on first load.
 *
 * PASSWORDS ARE NEVER HARDCODED HERE. They are read from SEED_*_PASSWORD
 * environment variables and the script refuses to run without them. Seeded
 * accounts are flagged `mustChangePassword`.
 *
 * HISTORICAL DATA IS CLEARLY MARKED. Seeded telemetry is generated by the same
 * physics engine and stamped `source: 'SIMULATION'`, so it can never be
 * mistaken for a measurement. The simulator then continues from where the seed
 * left off.
 */

import { SimulationEngine } from '../shared/simulation/engine';
import { COLLECTIONS, DEFAULT_BILLING } from '../shared/constants';
import { resolveNodes } from '../shared/nodes.config';
import { validateFrame } from '../shared/validation';
import type { Alert, Role, TelemetryFrame } from '../shared/types';
import { checkPasswordPolicy, hashPassword, newUserId } from '../server/auth';
import { closeClient, collection } from '../server/db';
import { env } from '../server/env';
import { alertRepo, telemetryRepo, userRepo, type UserDocument } from '../server/repositories';

const ROLES: Role[] = ['ADMIN', 'OPERATOR', 'TECHNICIAN', 'VIEWER'];

/** Hours of history to backfill. */
const HISTORY_HOURS = 6;

async function seedUsers(): Promise<void> {
  console.log('\nUsers');

  const missing: string[] = [];
  for (const role of ROLES) {
    if (!env.seedUser(role)) missing.push(`SEED_${role}_EMAIL / SEED_${role}_PASSWORD`);
  }
  if (missing.length === ROLES.length) {
    throw new Error(
      `No seed credentials configured. Set these in .env before seeding:\n  ${missing.join('\n  ')}`,
    );
  }

  for (const role of ROLES) {
    const creds = env.seedUser(role);
    if (!creds) {
      console.log(`  [skip] ${role} — no credentials configured`);
      continue;
    }

    const policy = checkPasswordPolicy(creds.password);
    if (!policy.ok) {
      console.log(`  [FAIL] ${role} — password ${policy.problems.join(', ')}`);
      continue;
    }

    const existing = await userRepo.findByEmail(creds.email);
    if (existing) {
      console.log(`  [keep] ${role.padEnd(10)} ${creds.email} (already exists)`);
      continue;
    }

    const user: UserDocument = {
      id: newUserId(),
      name: `${role.charAt(0)}${role.slice(1).toLowerCase()} User`,
      email: creds.email.toLowerCase(),
      role,
      provider: 'password',
      createdAt: new Date().toISOString(),
      passwordHash: await hashPassword(creds.password),
      // Seeded credentials are for local demo use only.
      mustChangePassword: true,
    };

    await userRepo.create(user);
    console.log(`  [new]  ${role.padEnd(10)} ${creds.email}`);
  }

  console.log('\n  Seeded accounts are flagged mustChangePassword.');
  console.log('  Credentials live in your local .env and are never committed.');
}

async function seedNodes(): Promise<void> {
  console.log('\nNodes');
  const nodes = resolveNodes(env.simulationNodeCount);
  const col = await collection(COLLECTIONS.nodes);

  for (const node of nodes) {
    await col.updateOne({ id: node.id } as never, { $set: node as never }, { upsert: true });
    console.log(`  ${node.shortName.padEnd(10)} ${node.type.padEnd(9)} ${node.ratedPower} W`);
  }
}

async function seedTelemetry(): Promise<TelemetryFrame[]> {
  console.log(`\nTelemetry (${HISTORY_HOURS} h of history)`);

  const nodeCount = env.simulationNodeCount;
  const nodes = resolveNodes(nodeCount);

  // Wall-clock spacing between seeded frames. 30 s keeps the document count
  // reasonable (720 ticks) while still giving charts a smooth line.
  const stepMs = 30_000;
  const ticks = Math.floor((HISTORY_HOURS * 3600_000) / stepMs);
  const startWallClock = Date.now() - HISTORY_HOURS * 3600_000;

  const engine = new SimulationEngine({
    nodeCount,
    scenario: 'NORMAL',
    intervalMs: stepMs,
    // Simulated time advances at the same rate as the backfilled wall clock, so
    // the solar curve in the seeded history matches the real time of day.
    speed: 1,
    seed: 4242,
    startTime: new Date(startWallClock),
  });

  const frames: TelemetryFrame[] = [];

  for (let i = 0; i < ticks; i++) {
    const result = engine.tick();
    const wallClock = startWallClock + i * stepMs;

    for (const frame of result.frames) {
      const node = nodes.find((n) => n.id === frame.nodeId);
      // Rewrite the timestamp onto the historical wall clock: the engine stamps
      // frames with Date.now(), which would put all of this "history" in the
      // present and make every chart a vertical line.
      const stamped: TelemetryFrame = { ...frame, timestamp: new Date(wallClock).toISOString() };
      const validation = validateFrame(stamped, node);
      frames.push({
        ...stamped,
        valid: validation.valid,
        validationErrors: validation.valid ? undefined : validation.errors,
      });
    }
  }

  // Insert in batches so a single oversized request cannot fail the whole seed.
  let inserted = 0;
  const batchSize = 1000;
  for (let i = 0; i < frames.length; i += batchSize) {
    inserted += await telemetryRepo.insertMany(frames.slice(i, i + batchSize));
    process.stdout.write(`\r  inserted ${inserted}/${frames.length}`);
  }
  console.log(`\n  ${inserted} frames across ${nodes.length} nodes`);

  return frames;
}

async function seedAlerts(): Promise<void> {
  console.log('\nAlerts');

  // A small, clearly-labelled set of historical examples so the Alert Center is
  // not empty before the simulator raises its own. Each is a real rule id.
  const now = Date.now();
  const examples: Alert[] = [
    {
      id: `alrt_seed_${now}_1`,
      ruleId: 'SOLAR_LOW_YIELD',
      nodeId: 'sigma',
      timestamp: new Date(now - 3 * 3600_000).toISOString(),
      severity: 'WARNING',
      source: 'RULE',
      kind: 'DETECTED',
      condition: 'Generation below irradiance expectation',
      actualValue: 62,
      expectedValue: 75,
      unit: '%',
      message:
        'SIGMA delivered 62 % of the power the model expected for the measured irradiance (seeded example).',
      likelyCause:
        'Irradiance adequate but yield reduced, consistent with soiling or partial shading. Inference from the power/irradiance relationship, not a physical inspection.',
      recommendedAction:
        'Inspect the panel surface for dust or soiling and verify string wiring integrity.',
      status: 'RESOLVED',
      resolvedBy: 'seed',
      resolvedAt: new Date(now - 2 * 3600_000).toISOString(),
    },
    {
      id: `alrt_seed_${now}_2`,
      ruleId: 'BATTERY_LOW_SOC',
      nodeId: 'beta',
      timestamp: new Date(now - 90 * 60_000).toISOString(),
      severity: 'WARNING',
      source: 'RULE',
      kind: 'DETECTED',
      condition: 'Battery state of charge low',
      actualValue: 27,
      expectedValue: 30,
      unit: '%',
      message: 'BETA state of charge fell to 27 % overnight (seeded example).',
      likelyCause: 'Demand exceeded generation through the evening peak.',
      recommendedAction: 'Reduce non-critical load to preserve reserve capacity.',
      status: 'ACKNOWLEDGED',
      acknowledgedBy: 'seed',
      acknowledgedAt: new Date(now - 80 * 60_000).toISOString(),
    },
    {
      id: `alrt_seed_${now}_3`,
      ruleId: 'COMM_NODE_STALE',
      nodeId: 'dc_load',
      timestamp: new Date(now - 45 * 60_000).toISOString(),
      severity: 'WARNING',
      source: 'COMMUNICATION',
      kind: 'DETECTED',
      condition: 'Node data stale',
      actualValue: 14,
      expectedValue: 8,
      unit: 's',
      message: 'DC LOAD telemetry was 14 s old and no longer current (seeded example).',
      likelyCause:
        'COMMUNICATION fault: frames delayed or dropped in transit. The node itself may have been operating normally.',
      recommendedAction: 'Check link quality and broker latency.',
      status: 'RESOLVED',
      resolvedBy: 'seed',
      resolvedAt: new Date(now - 40 * 60_000).toISOString(),
    },
  ];

  const inserted = await alertRepo.insertMany(examples);
  console.log(`  ${inserted} example alert(s) (marked "seeded example" in their text)`);
}

async function seedSettings(): Promise<void> {
  console.log('\nSettings');
  const col = await collection(COLLECTIONS.settings);
  await col.updateOne(
    { _id: 'billing' as never },
    { $set: { assumptions: DEFAULT_BILLING, updatedAt: new Date() } },
    { upsert: true },
  );
  console.log('  Default billing assumptions stored (all user-editable).');
}

async function main(): Promise<void> {
  console.log('='.repeat(64));
  console.log('GridSync database seed');
  console.log('='.repeat(64));
  console.log(`\nDatabase: ${env.dbName}`);

  await seedUsers();
  await seedNodes();
  await seedTelemetry();
  await seedAlerts();
  await seedSettings();

  console.log('\n' + '='.repeat(64));
  console.log('Seed complete.');
  console.log('\nNOTE: seeded telemetry is SIMULATION output, not measurement.');
  console.log('Start the simulator to continue generating live data:');
  console.log('  npm run worker');
  console.log('='.repeat(64));

  await closeClient();
}

main().catch(async (err) => {
  console.error('\nSeed failed:', err instanceof Error ? err.message : err);
  await closeClient();
  process.exit(1);
});
