"""
Random Forest fault classifier — training.

Run:  npm run ml:train     (or: python ml/training/train_classifier.py)

WHAT THIS PRODUCES
    ml/models/v<N>/model.joblib          fitted sklearn estimator
    ml/models/v<N>/model.json            portable tree dump for the Node runtime
    ml/models/v<N>/sklearn_sample.json   held-out rows + sklearn predictions,
                                         used to prove the TS evaluator matches
    ml/models/current.json               pointer to the promoted version

HONESTY NOTES — please read before quoting any number this produces
  * The training data is SYNTHETIC, generated by GridSync's own physics model.
    Every artefact is stamped `trained_on_synthetic_data: true` and the UI
    surfaces that flag next to every prediction.
  * Accuracy on synthetic data measures how separable the simulator's scenario
    regimes are. It is NOT evidence of real-world fault-detection performance
    and must never be presented as such.
  * Metrics are computed by ml/evaluation/evaluate.py on a held-out TEST split
    that is grouped by episode. Nothing here is hand-written.
  * Model selection uses the VALIDATION split only. The test split is touched
    exactly once, by the evaluation script.
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
import joblib

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from features.feature_engineering import (  # noqa: E402
    FEATURE_ORDER,
    Dataset,
    describe_split,
    load_dataset,
    split_by_episode,
)
from models.model_registry import next_version, set_current  # noqa: E402

RANDOM_STATE = 42


def build_model(n_estimators: int, max_depth: int | None, min_samples_leaf: int) -> RandomForestClassifier:
    return RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_leaf=min_samples_leaf,
        # The dataset is ~68 % NORMAL. Without rebalancing, the forest would
        # maximise accuracy by under-predicting exactly the rare fault classes
        # the product exists to catch.
        class_weight="balanced_subsample",
        n_jobs=-1,
        random_state=RANDOM_STATE,
    )


def select_model(ds: Dataset) -> tuple[RandomForestClassifier, dict]:
    """
    Small grid search scored on the VALIDATION split.

    Macro-F1 is the selection metric, not accuracy: with a dominant NORMAL
    class, accuracy rewards a model that ignores the faults.
    """
    # Depth and leaf size are bounded deliberately. An unbounded forest scored
    # marginally better but exported a 30 MB portable JSON, which is far too
    # large to ship into a serverless function. These settings keep the export
    # in the low single-digit MB while costing very little macro-F1.
    grid = [
        {"n_estimators": 60, "max_depth": 10, "min_samples_leaf": 10},
        {"n_estimators": 80, "max_depth": 10, "min_samples_leaf": 8},
        {"n_estimators": 100, "max_depth": 12, "min_samples_leaf": 8},
        {"n_estimators": 120, "max_depth": 12, "min_samples_leaf": 6},
        {"n_estimators": 100, "max_depth": 14, "min_samples_leaf": 6},
        {"n_estimators": 150, "max_depth": 14, "min_samples_leaf": 4},
        {"n_estimators": 150, "max_depth": 16, "min_samples_leaf": 3},
    ]

    results = []

    print("\nModel selection (scored on validation split, macro-F1):")
    for params in grid:
        model = build_model(**params)
        model.fit(ds.X_train, ds.y_train)
        pred = model.predict(ds.X_val)
        score = float(f1_score(ds.y_val, pred, average="macro", zero_division=0))
        # Total node count is a direct proxy for exported JSON size.
        nodes = int(sum(est.tree_.node_count for est in model.estimators_))
        print(f"  {params}  ->  macro-F1 {score:.4f}  ({nodes:,} nodes)")
        results.append({"params": params, "model": model, "score": score, "nodes": nodes})

    best_score = max(r["score"] for r in results)

    # Size-aware selection under a HARD deployment budget.
    #
    # The portable JSON is loaded by a Vercel serverless function, so its size
    # is a real constraint, not a preference. Roughly 45 bytes per tree node in
    # the export puts 60k nodes at about 3 MB, which is comfortable. Among the
    # models that fit, take the most accurate; only if none fit do we take the
    # smallest and say so.
    NODE_BUDGET = 60_000

    affordable = [r for r in results if r["nodes"] <= NODE_BUDGET]
    if affordable:
        chosen = max(affordable, key=lambda r: r["score"])
    else:
        chosen = min(results, key=lambda r: r["nodes"])
        print(
            f"\nWARNING: no candidate fits the {NODE_BUDGET:,}-node deployment "
            "budget; selecting the smallest available."
        )

    if chosen["score"] < best_score:
        print(
            f"\nBest macro-F1 was {best_score:.4f} but that model has "
            f"{max(r['nodes'] for r in results):,} nodes, over the "
            f"{NODE_BUDGET:,} deployment budget. Selected the best model that fits."
        )

    print(f"\nSelected: {chosen['params']}  (validation macro-F1 {chosen['score']:.4f}, {chosen['nodes']:,} nodes)")
    return chosen["model"], {
        **chosen["params"],
        "validation_macro_f1": round(chosen["score"], 6),
        "best_validation_macro_f1": round(best_score, 6),
        "total_tree_nodes": chosen["nodes"],
        "node_budget": NODE_BUDGET,
        "selection_rule": (
            f"highest validation macro-F1 among candidates within the "
            f"{NODE_BUDGET:,}-node portable-export budget"
        ),
    }


def export_portable(model: RandomForestClassifier, version: str, classes: list[str]) -> dict:
    """
    Dump the fitted forest into plain JSON that shared/ml/forest.ts can walk.

    sklearn stores each tree as parallel arrays. We copy them verbatim so the
    TypeScript evaluator can reproduce the traversal exactly:
      children_left[i] == -1  ->  node i is a leaf
      value[i]                ->  class counts at node i
    """
    trees = []
    for estimator in model.estimators_:
        t = estimator.tree_
        # value has shape (n_nodes, 1, n_classes); squeeze the middle axis.
        value = t.value.reshape(t.value.shape[0], t.value.shape[2])
        children_left = t.children_left.astype(int).tolist()

        # Inference only ever reads `value` at a LEAF, so internal nodes ship as
        # an empty array. With ~half the nodes internal and 11 classes each,
        # this removes a large fraction of the payload for free.
        values_out = [
            [round(float(v), 4) for v in value[i].tolist()] if children_left[i] == -1 else []
            for i in range(len(children_left))
        ]
        # Thresholds keep FULL precision. Rounding them would move split points
        # relative to feature values and could route a sample down a different
        # branch than sklearn does, breaking the parity guarantee that
        # tests/forest.test.ts enforces. Leaves carry no threshold, so those
        # slots are zeroed instead.
        thresholds = [
            float(x) if children_left[i] != -1 else 0.0
            for i, x in enumerate(t.threshold.tolist())
        ]

        trees.append(
            {
                "feature": t.feature.astype(int).tolist(),
                "threshold": thresholds,
                "childLeft": children_left,
                "childRight": t.children_right.astype(int).tolist(),
                "value": values_out,
            }
        )

    return {
        "modelVersion": version,
        "algorithm": "RandomForestClassifier (scikit-learn)",
        "featureOrder": list(FEATURE_ORDER),
        "classes": classes,
        "trees": trees,
        "featureImportances": [round(float(x), 8) for x in model.feature_importances_.tolist()],
        "trainedOnSyntheticData": True,
        "trainedAt": datetime.now(timezone.utc).isoformat(),
    }


def export_parity_sample(
    model: RandomForestClassifier, ds: Dataset, n: int = 200
) -> dict:
    """
    A held-out sample plus sklearn's own outputs.

    tests/forest.test.ts replays these rows through the TypeScript evaluator and
    asserts identical predictions. This is what stops the two inference paths
    diverging without anybody noticing.
    """
    rng = np.random.default_rng(RANDOM_STATE)
    idx = rng.choice(len(ds.X_test), size=min(n, len(ds.X_test)), replace=False)
    X = ds.X_test[idx]
    proba = model.predict_proba(X)
    pred = model.predict(X)

    return {
        "featureOrder": list(FEATURE_ORDER),
        "classes": list(model.classes_),
        "rows": [
            {
                "features": [round(float(v), 8) for v in X[i].tolist()],
                "sklearnPrediction": str(pred[i]),
                "sklearnProbabilities": [round(float(p), 8) for p in proba[i].tolist()],
            }
            for i in range(len(X))
        ],
    }


def main() -> int:
    print("=" * 70)
    print("GridSync — Random Forest fault classifier training")
    print("=" * 70)
    print("\nWARNING: training data is SYNTHETIC (generated by GridSync's own")
    print("physics model). Metrics describe scenario separability, not")
    print("validated real-world fault-detection performance.\n")

    df = load_dataset()
    ds = split_by_episode(df)
    print(describe_split(ds))

    model, selection = select_model(ds)

    version_dir = next_version()
    version = version_dir.version
    classes = [str(c) for c in model.classes_]

    joblib.dump(model, version_dir.model_joblib)

    portable = export_portable(model, version, classes)
    with open(version_dir.model_json, "w", encoding="utf-8") as f:
        json.dump(portable, f, separators=(",", ":"))

    parity = export_parity_sample(model, ds)
    with open(version_dir.sample_json, "w", encoding="utf-8") as f:
        json.dump(parity, f, separators=(",", ":"))

    # Record how this model was produced so evaluate.py can reuse the split.
    with open(os.path.join(version_dir.path, "training_meta.json"), "w", encoding="utf-8") as f:
        json.dump(
            {
                "version": version,
                "selection": selection,
                "randomState": RANDOM_STATE,
                "datasetRows": int(len(df)),
                "episodes": ds.n_episodes,
                "trainedAt": datetime.now(timezone.utc).isoformat(),
                "trainedOnSyntheticData": True,
            },
            f,
            indent=2,
        )

    set_current(version)

    size_mb = os.path.getsize(version_dir.model_json) / 1_000_000
    print(f"\nSaved model version {version}")
    print(f"  {version_dir.model_joblib}")
    print(f"  {version_dir.model_json}  ({size_mb:.2f} MB portable)")
    print(f"  {version_dir.sample_json}")
    print(f"\nPromoted {version} as current.")
    print("\nNext: npm run ml:evaluate   (computes the real held-out metrics)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
